language: node_js
node_js:
  - 8
  - 9
  - 10
cache:
  directories:
    - node_modules
script:
  - yarn run lint
  - yarn run test-cov
after_script:
  - yarn install codecov
  - ./node_modules/.bin/codecov